# This is a basic workflow to help you get started with Actions

name: sample-book-app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build

      # - name: --- build success ---
      #   run: echo Building of node application is starting ...
      
      # - name: --- check node and npm version ---
      #   run: |
      #     node -v
      #     npm -v
      #     pm2 delete ${enviroment}
      #     pm2 start -n \"${enviroment}\" index.js -- ${port}


  deploy-dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          port: 2345
          enviroment: 'DEV'

  tests-dev:
    name: Tests DEV
    runs-on: ubuntu-latest
    needs: [deploy-dev]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          enviroment: 'DEV'
  
  deploy-stg:
    name: Deploy STG
    runs-on: ubuntu-latest
    needs: [tests-dev]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          port: 6789
          enviroment: 'STG'

  tests-stg:
    name: Tests STG
    runs-on: ubuntu-latest
    needs: [deploy-stg]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          enviroment: 'STG'

  deploy-prd:
    name: Deploy PRD
    runs-on: ubuntu-latest
    needs: [tests-stg]
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          port: 1111
          enviroment: 'PRD'

  tests-prd:
    name: Tests PRD
    runs-on: ubuntu-latest
    needs: [deploy-prd]
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          enviroment: 'PRD'

